python3 tf_mlp.py 1 arousal without_base
python3 tf_mlp.py 2 arousal without_base
python3 tf_mlp.py 3 arousal without_base
python3 tf_mlp.py 4 arousal without_base
python3 tf_mlp.py 5 arousal without_base
python3 tf_mlp.py 6 arousal without_base
python3 tf_mlp.py 7 arousal without_base
python3 tf_mlp.py 8 arousal without_base
python3 tf_mlp.py 9 arousal without_base
python3 tf_mlp.py 10 arousal without_base
python3 tf_mlp.py 11 arousal without_base
python3 tf_mlp.py 12 arousal without_base
python3 tf_mlp.py 13 arousal without_base
python3 tf_mlp.py 14 arousal without_base
python3 tf_mlp.py 15 arousal without_base
python3 tf_mlp.py 16 arousal without_base
python3 tf_mlp.py 17 arousal without_base
python3 tf_mlp.py 18 arousal without_base
python3 tf_mlp.py 19 arousal without_base
python3 tf_mlp.py 20 arousal without_base
python3 tf_mlp.py 21 arousal without_base
python3 tf_mlp.py 22 arousal without_base
python3 tf_mlp.py 23 arousal without_base
python3 tf_mlp.py 24 arousal without_base
python3 tf_mlp.py 25 arousal without_base
python3 tf_mlp.py 26 arousal without_base
python3 tf_mlp.py 27 arousal without_base
python3 tf_mlp.py 28 arousal without_base
python3 tf_mlp.py 29 arousal without_base
python3 tf_mlp.py 30 arousal without_base
python3 tf_mlp.py 31 arousal without_base
python3 tf_mlp.py 32 arousal without_base
