python3 tf_mlp.py 01 arousal with_base
python3 tf_mlp.py 02 arousal with_base
python3 tf_mlp.py 03 arousal with_base
python3 tf_mlp.py 04 arousal with_base
python3 tf_mlp.py 05 arousal with_base
python3 tf_mlp.py 06 arousal with_base
python3 tf_mlp.py 07 arousal with_base
python3 tf_mlp.py 08 arousal with_base
python3 tf_mlp.py 09 arousal with_base
python3 tf_mlp.py 10 arousal with_base
python3 tf_mlp.py 11 arousal with_base
python3 tf_mlp.py 12 arousal with_base
python3 tf_mlp.py 13 arousal with_base
python3 tf_mlp.py 14 arousal with_base
python3 tf_mlp.py 15 arousal with_base
python3 tf_mlp.py 16 arousal with_base
python3 tf_mlp.py 17 arousal with_base
python3 tf_mlp.py 18 arousal with_base
python3 tf_mlp.py 19 arousal with_base
python3 tf_mlp.py 20 arousal with_base
python3 tf_mlp.py 21 arousal with_base
python3 tf_mlp.py 22 arousal with_base
python3 tf_mlp.py 23 arousal with_base
python3 tf_mlp.py 24 arousal with_base
python3 tf_mlp.py 25 arousal with_base
python3 tf_mlp.py 26 arousal with_base
python3 tf_mlp.py 27 arousal with_base
python3 tf_mlp.py 28 arousal with_base
python3 tf_mlp.py 29 arousal with_base
python3 tf_mlp.py 30 arousal with_base
python3 tf_mlp.py 31 arousal with_base
python3 tf_mlp.py 32 arousal with_base
