python3 tf_mlp_channels.py 20 arousal with_base 1
python3 tf_mlp_channels.py 21 arousal with_base 1
python3 tf_mlp_channels.py 22 arousal with_base 1
python3 tf_mlp_channels.py 23 arousal with_base 1
python3 tf_mlp_channels.py 24 arousal with_base 1
python3 tf_mlp_channels.py 25 arousal with_base 1
python3 tf_mlp_channels.py 26 arousal with_base 1
python3 tf_mlp_channels.py 27 arousal with_base 1
python3 tf_mlp_channels.py 28 arousal with_base 1
python3 tf_mlp_channels.py 29 arousal with_base 1
python3 tf_mlp_channels.py 30 arousal with_base 1
python3 tf_mlp_channels.py 31 arousal with_base 1
python3 tf_mlp_channels.py 32 arousal with_base 1
python3 tf_mlp_channels.py 01 arousal without_base 1
python3 tf_mlp_channels.py 02 arousal without_base 1
python3 tf_mlp_channels.py 03 arousal without_base 1
python3 tf_mlp_channels.py 04 arousal without_base 1
python3 tf_mlp_channels.py 05 arousal without_base 1
python3 tf_mlp_channels.py 06 arousal without_base 1
python3 tf_mlp_channels.py 07 arousal without_base 1
python3 tf_mlp_channels.py 08 arousal without_base 1
python3 tf_mlp_channels.py 09 arousal without_base 1
python3 tf_mlp_channels.py 10 arousal without_base 1
python3 tf_mlp_channels.py 11 arousal without_base 1
python3 tf_mlp_channels.py 12 arousal without_base 1
python3 tf_mlp_channels.py 13 arousal without_base 1
python3 tf_mlp_channels.py 14 arousal without_base 1
python3 tf_mlp_channels.py 15 arousal without_base 1
python3 tf_mlp_channels.py 16 arousal without_base 1
python3 tf_mlp_channels.py 17 arousal without_base 1
python3 tf_mlp_channels.py 18 arousal without_base 1
python3 tf_mlp_channels.py 19 arousal without_base 1
python3 tf_mlp_channels.py 20 arousal without_base 1
python3 tf_mlp_channels.py 21 arousal without_base 1
python3 tf_mlp_channels.py 22 arousal without_base 1
python3 tf_mlp_channels.py 23 arousal without_base 1
python3 tf_mlp_channels.py 24 arousal without_base 1
python3 tf_mlp_channels.py 25 arousal without_base 1
python3 tf_mlp_channels.py 26 arousal without_base 1
python3 tf_mlp_channels.py 27 arousal without_base 1